import { useEffect, useState } from 'react'
import { Activity, Brain, CheckCircle2, Cpu, LockKeyhole, Play, RefreshCw, Wrench, X } from 'lucide-react'
import './agent.css'

type Skill={id:string;label:string;tool:string;status:string;executable:boolean;agentId:string;departmentId:string}
type Run={id:string;skill:string;status:string;output?:string|null;input?:string|null;createdAt:string}
type Task={id:string;title:string;status:string;priority:string;department:string;owner:string}
type Agent={id:string;name:string;role:string;status:string;task?:string|null}
type Department={id:string;name:string;lead:string;accent:string;agents:Agent[]}
type State={departments:Department[];tasks:Task[]}
type BrainItem={id:string;scope:string;departmentId?:string|null}
type Profile={agent:Agent;department:Department;skills:Skill[];tools:string[];permissions:string[];memoryScope:string;currentTasks:Task[];recentRuns:Run[];brainCount:number;lead:boolean}

const planned:Record<string,Skill[]>={
  m1:[{id:'lead.durable-delegation',agentId:'m1',departmentId:'marketing',label:'Durable Delegation',tool:'Command Center',status:'ready',executable:false}],
  m2:[{id:'marketing.market-research',agentId:'m2',departmentId:'marketing',label:'Market Research',tool:'Browser',status:'planned',executable:false}],
  m3:[{id:'marketing.creative-brief',agentId:'m3',departmentId:'marketing',label:'Creative Brief',tool:'Brain',status:'planned',executable:false}],
  m4:[{id:'marketing.copy-draft',agentId:'m4',departmentId:'marketing',label:'Campaign Copy Draft',tool:'Brain',status:'planned',executable:false}],
  m5:[{id:'marketing.social-calendar',agentId:'m5',departmentId:'marketing',label:'Social Calendar',tool:'Brain',status:'planned',executable:false}],
  m6:[{id:'marketing.seo-map',agentId:'m6',departmentId:'marketing',label:'SEO Opportunity Map',tool:'Browser',status:'planned',executable:false}],
  m7:[{id:'marketing.performance-summary',agentId:'m7',departmentId:'marketing',label:'Performance Summary',tool:'Analytics',status:'planned',executable:false}],
  s1:[{id:'sales.pipeline-review',agentId:'s1',departmentId:'sales',label:'Pipeline Review',tool:'CRM',status:'planned',executable:false}],
  f1:[{id:'finance.cashflow-brief',agentId:'f1',departmentId:'finance',label:'Cashflow Brief',tool:'Finance Data',status:'planned',executable:false}],
  c1:[{id:'support.inbox-triage',agentId:'c1',departmentId:'support',label:'Inbox Triage',tool:'Gmail',status:'planned',executable:false}]
}

const normalizeSkill=(raw:any):Skill=>({id:raw.id,agentId:raw.agentId,departmentId:raw.departmentId,label:raw.label||raw.id,tool:raw.tool||'Command Center',status:raw.status||(['github.repo-audit','operations.release-gate'].includes(raw.id)?'ready':'planned'),executable:raw.executable??['github.repo-audit','operations.release-gate'].includes(raw.id)})

export default function AgentDrawer({agentId,onClose}:{agentId:string;onClose:()=>void}){
  const [profile,setProfile]=useState<Profile|null>(null)
  const [busy,setBusy]=useState(false)
  const [note,setNote]=useState('')
  const load=async()=>{setBusy(true);setNote('');try{const [stateRes,skillsRes,runsRes,brainRes]=await Promise.all([fetch('/api/state'),fetch('/api/skills'),fetch(`/api/runs?agent=${agentId}`),fetch('/api/brain')]);if(!stateRes.ok)throw new Error('state_unavailable');const state:State=await stateRes.json();const dept=state.departments.find(d=>d.agents.some(a=>a.id===agentId));const agent=dept?.agents.find(a=>a.id===agentId);if(!dept||!agent)throw new Error('agent_not_found');const liveSkills=skillsRes.ok?(await skillsRes.json()).filter((s:any)=>s.agentId===agentId).map(normalizeSkill):[];const extras=(planned[agentId]||[]).filter(s=>!liveSkills.some((x:Skill)=>x.id===s.id));const skills=[...liveSkills,...extras];const recentRuns:Run[]=runsRes.ok?await runsRes.json():[];const brain:BrainItem[]=brainRes.ok?await brainRes.json():[];const lead=dept.lead===agent.name;const permissions=lead?['brain.read','task.create','task.update','approval.request','agent.delegate']:['brain.read:scope','task.update:own','tool.execute:assigned'];if(agent.id==='e1')permissions.push('github.read','brain.write:analysis');if(agent.id==='o1')permissions.push('github.read','workspace.read','approvals.read','brain.write:analysis');const memoryScope=lead?'organization + department':'department scoped';setProfile({agent,department:dept,skills,tools:[...new Set(skills.map(s=>s.tool))],permissions,memoryScope,currentTasks:state.tasks.filter(t=>t.owner===agent.name&&t.status!=='Done'),recentRuns,brainCount:brain.filter(item=>item.scope==='organization'||item.departmentId===dept.id).length,lead})}catch(e){setNote(e instanceof Error?e.message:'Profile unavailable')}finally{setBusy(false)}}
  useEffect(()=>{load()},[agentId])
  const runSkill=async(skill:Skill)=>{if(!profile)return;setBusy(true);setNote('');try{const r=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agentId:profile.agent.id,departmentId:profile.department.id,skill:skill.id,input:`Run ${skill.label} from agent profile.`})});const d=await r.json();if(!r.ok)throw new Error(d.output||d.error||'agent_run_failed');setNote(`${profile.agent.name} completed ${skill.label}.`);await load()}catch(e){setNote(e instanceof Error?e.message:'Run failed')}finally{setBusy(false)}}
  return <div className="agent-drawer-backdrop" onMouseDown={onClose}><aside className="agent-drawer" onMouseDown={e=>e.stopPropagation()}><div className="agent-drawer-head"><div><span>AGENT PROFILE</span><h2>{profile?.agent.name||'Loading…'}</h2><p>{profile?`${profile.agent.role} · ${profile.department.name}`:'Resolving live capability profile'}</p></div><button onClick={onClose}><X/></button></div>{!profile?<div className="agent-loading"><RefreshCw className={busy?'spin':''}/> Loading durable profile…</div>:<><div className="agent-identity"><div className="agent-monogram" style={{borderColor:profile.department.accent}}>{profile.agent.name[0]}</div><div><b>{profile.agent.name}</b><span className={`agent-state ${profile.agent.status}`}>{profile.agent.status}</span><p>{profile.lead?'Department Lead':'Specialist Agent'} · Memory: {profile.memoryScope}</p></div></div><div className="agent-kpis"><div><Brain/><b>{profile.brainCount}</b><span>Brain items</span></div><div><Activity/><b>{profile.recentRuns.length}</b><span>Recent runs</span></div><div><Cpu/><b>{profile.currentTasks.length}</b><span>Active tasks</span></div></div><section><div className="agent-section-title"><Cpu/> Skills</div><div className="skill-stack">{profile.skills.length?profile.skills.map(skill=><div className="skill-row" key={skill.id}><div><b>{skill.label}</b><span>{skill.tool}</span></div><div className="skill-actions"><em className={skill.status}>{skill.status}</em>{skill.executable&&<button disabled={busy} onClick={()=>runSkill(skill)}><Play/>Run</button>}</div></div>):<div className="agent-empty">No registered skills yet.</div>}</div></section><section><div className="agent-section-title"><Wrench/> Tool permissions</div><div className="chip-grid">{profile.tools.map(t=><span key={t}>{t}</span>)}{profile.tools.length===0&&<span>Brain only</span>}</div></section><section><div className="agent-section-title"><LockKeyhole/> Permissions</div><div className="chip-grid permissions">{profile.permissions.map(p=><span key={p}>{p}</span>)}</div></section><section><div className="agent-section-title"><CheckCircle2/> Current work</div><div className="agent-task-list">{profile.currentTasks.length?profile.currentTasks.map(t=><div key={t.id}><b>{t.title}</b><span>{t.status} · {t.priority}</span></div>):<div className="agent-empty">No active durable tasks.</div>}</div></section><section><div className="agent-section-title"><Activity/> Execution history</div><div className="agent-run-list">{profile.recentRuns.length?profile.recentRuns.slice(0,6).map(r=><div key={r.id}><em className={r.status}>{r.status}</em><div><b>{r.skill}</b><p>{r.output||r.input||'No output'}</p></div></div>):<div className="agent-empty">No runs recorded yet.</div>}</div></section></>}{note&&<div className="agent-note">{note}</div>}</aside></div>
}
