import { useEffect, useMemo, useState } from 'react'
import { Activity, Brain, CheckCircle2, Cpu, LockKeyhole, Play, Plus, RefreshCw, Replace, ToggleLeft, ToggleRight, Wrench, X } from 'lucide-react'
import './agent.css'

type Skill={assignmentId:string;id:string;slot:string;skillKey:string;version:number;label:string;description?:string|null;tool:string;status:string;executable:boolean;approvalRequired:boolean;permissions:string[];enabled:boolean;engineAvailable:boolean}
type Run={id:string;skill:string;skillVersion?:number|null;status:string;output?:string|null;input?:string|null;createdAt:string}
type Task={id:string;title:string;status:string;priority:string;department:string}
type Profile={agent:{id:string;name:string;role:string;status:string;task?:string|null};department:{id:string;name:string;lead:string;accent:string};capabilities:{lead:boolean;skills:Skill[];tools:string[];permissions:string[];memoryScope:string};currentTasks:Task[];recentRuns:Run[];brain:{accessibleItems:number;scope:string}}
type SkillDraft={slot:string;skillKey:string;version:string;label:string;tool:string;status:string;executable:boolean;approvalRequired:boolean;permissions:string}

const emptyDraft:SkillDraft={slot:'secondary',skillKey:'',version:'',label:'',tool:'Brain',status:'draft',executable:false,approvalRequired:false,permissions:''}

export default function AgentDrawer({agentId,onClose}:{agentId:string;onClose:()=>void}){
  const [profile,setProfile]=useState<Profile|null>(null)
  const [busy,setBusy]=useState(false)
  const [note,setNote]=useState('')
  const [draft,setDraft]=useState<SkillDraft|null>(null)

  const load=async()=>{setBusy(true);setNote('');try{const r=await fetch(`/api/agents/${agentId}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'agent_profile_failed');setProfile(d)}catch(e){setNote(e instanceof Error?e.message:'Profile unavailable')}finally{setBusy(false)}}
  useEffect(()=>{load()},[agentId])
  const runnable=useMemo(()=>new Set((profile?.capabilities.skills||[]).filter(s=>s.enabled&&s.status==='ready'&&s.executable&&s.engineAvailable).map(s=>s.assignmentId)),[profile])

  const runSkill=async(skill:Skill)=>{if(!profile)return;setBusy(true);setNote('');try{const r=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agentId:profile.agent.id,departmentId:profile.department.id,skill:skill.skillKey,input:`Run ${skill.label} v${skill.version} from agent profile.`})});const d=await r.json();if(!r.ok)throw new Error(d.output||d.error||'agent_run_failed');setNote(`${profile.agent.name} completed ${skill.label} v${skill.version}.`);await load()}catch(e){setNote(e instanceof Error?e.message:'Run failed')}finally{setBusy(false)}}
  const toggleSkill=async(skill:Skill)=>{setBusy(true);setNote('');try{const r=await fetch(`/api/agent-skills/${skill.assignmentId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({enabled:!skill.enabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'skill_toggle_failed');setNote(`${skill.label} ${skill.enabled?'disabled':'enabled'}.`);await load()}catch(e){setNote(e instanceof Error?e.message:'Skill update failed')}finally{setBusy(false)}}
  const startReplace=(skill:Skill)=>setDraft({slot:skill.slot,skillKey:skill.skillKey,version:String(skill.version+1),label:skill.label,tool:skill.tool,status:skill.status,executable:skill.executable,approvalRequired:skill.approvalRequired,permissions:skill.permissions.join(', ')})
  const saveSkill=async()=>{if(!profile||!draft||!draft.skillKey.trim()||!draft.label.trim())return;setBusy(true);setNote('');try{const body:any={skillKey:draft.skillKey.trim(),label:draft.label.trim(),tool:draft.tool.trim()||'Brain',status:draft.status,executable:draft.executable,approvalRequired:draft.approvalRequired,permissions:draft.permissions.split(',').map(v=>v.trim()).filter(Boolean)};if(draft.version.trim())body.version=Number(draft.version);const r=await fetch(`/api/agents/${profile.agent.id}/skills/${encodeURIComponent(draft.slot.trim()||'primary')}/replace`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'skill_replace_failed');setProfile(d);setDraft(null);setNote('Skill slot updated. Previous version remains preserved in execution history.')}catch(e){setNote(e instanceof Error?e.message:'Skill replace failed')}finally{setBusy(false)}}

  return <div className="agent-drawer-backdrop" onMouseDown={onClose}><aside className="agent-drawer" onMouseDown={e=>e.stopPropagation()}>
    <div className="agent-drawer-head"><div><span>AGENT PROFILE · REPLACEABLE SKILLS</span><h2>{profile?.agent.name||'Loading…'}</h2><p>{profile?`${profile.agent.role} · ${profile.department.name}`:'Resolving durable capability profile'}</p></div><button onClick={onClose}><X/></button></div>
    {!profile?<div className="agent-loading"><RefreshCw className={busy?'spin':''}/> Loading PostgreSQL capability profile…</div>:<>
      <div className="agent-identity"><div className="agent-monogram" style={{borderColor:profile.department.accent}}>{profile.agent.name[0]}</div><div><b>{profile.agent.name}</b><span className={`agent-state ${profile.agent.status}`}>{profile.agent.status}</span><p>{profile.capabilities.lead?'Department Lead':'Specialist Agent'} · Memory: {profile.capabilities.memoryScope}</p></div></div>
      <div className="agent-kpis"><div><Brain/><b>{profile.brain.accessibleItems}</b><span>Brain items</span></div><div><Activity/><b>{profile.recentRuns.length}</b><span>Recent runs</span></div><div><Cpu/><b>{profile.currentTasks.length}</b><span>Active tasks</span></div></div>
      <section><div className="agent-section-heading"><div className="agent-section-title"><Cpu/> Skill slots</div><button className="skill-add" onClick={()=>setDraft({...emptyDraft})}><Plus/>Add skill</button></div><div className="skill-stack">{profile.capabilities.skills.length?profile.capabilities.skills.map(skill=><div className={`skill-row ${skill.enabled?'':'disabled'}`} key={skill.assignmentId}><div className="skill-copy"><b>{skill.label} <small>v{skill.version}</small></b><span>{skill.slot} · {skill.skillKey}</span><span>{skill.tool}{skill.approvalRequired?' · approval required':''}</span></div><div className="skill-actions"><em className={skill.status}>{skill.status}</em><button className="icon-action" disabled={busy} title={skill.enabled?'Disable':'Enable'} onClick={()=>toggleSkill(skill)}>{skill.enabled?<ToggleRight/>:<ToggleLeft/>}</button><button className="replace-action" disabled={busy} onClick={()=>startReplace(skill)}><Replace/>Replace</button>{runnable.has(skill.assignmentId)&&<button disabled={busy} onClick={()=>runSkill(skill)}><Play/>Run</button>}</div></div>):<div className="agent-empty">No registered skills yet. Add a skill slot to begin.</div>}</div></section>
      <section><div className="agent-section-title"><Wrench/> Tool permissions</div><div className="chip-grid">{profile.capabilities.tools.map(t=><span key={t}>{t}</span>)}{profile.capabilities.tools.length===0&&<span>Brain only</span>}</div></section>
      <section><div className="agent-section-title"><LockKeyhole/> Effective permissions</div><div className="chip-grid permissions">{profile.capabilities.permissions.map(p=><span key={p}>{p}</span>)}</div></section>
      <section><div className="agent-section-title"><CheckCircle2/> Current work</div><div className="agent-task-list">{profile.currentTasks.length?profile.currentTasks.map(t=><div key={t.id}><b>{t.title}</b><span>{t.status} · {t.priority}</span></div>):<div className="agent-empty">No active durable tasks.</div>}</div></section>
      <section><div className="agent-section-title"><Activity/> Execution history</div><div className="agent-run-list">{profile.recentRuns.length?profile.recentRuns.slice(0,8).map(r=><div key={r.id}><em className={r.status}>{r.status}</em><div><b>{r.skill}{r.skillVersion?` · v${r.skillVersion}`:''}</b><p>{r.output||r.input||'No output'}</p></div></div>):<div className="agent-empty">No runs recorded yet.</div>}</div></section>
    </>}
    {draft&&<div className="skill-editor"><div className="skill-editor-head"><div><span>SKILL SLOT EDITOR</span><b>{draft.slot}</b></div><button onClick={()=>setDraft(null)}><X/></button></div><label>Slot<input value={draft.slot} onChange={e=>setDraft({...draft,slot:e.target.value})}/></label><label>Skill key<input value={draft.skillKey} onChange={e=>setDraft({...draft,skillKey:e.target.value})} placeholder="department.skill-name"/></label><div className="skill-form-grid"><label>Label<input value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label>Version<input type="number" min="1" value={draft.version} onChange={e=>setDraft({...draft,version:e.target.value})} placeholder="auto"/></label></div><div className="skill-form-grid"><label>Tool<input value={draft.tool} onChange={e=>setDraft({...draft,tool:e.target.value})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>draft</option><option>planned</option><option>ready</option><option>deprecated</option></select></label></div><label>Permissions<input value={draft.permissions} onChange={e=>setDraft({...draft,permissions:e.target.value})} placeholder="brain.read, browser.read"/></label><div className="skill-flags"><label><input type="checkbox" checked={draft.executable} onChange={e=>setDraft({...draft,executable:e.target.checked})}/>Executable</label><label><input type="checkbox" checked={draft.approvalRequired} onChange={e=>setDraft({...draft,approvalRequired:e.target.checked})}/>Requires approval</label></div><div className="skill-editor-actions"><button className="ghost" onClick={()=>setDraft(null)}>Cancel</button><button className="primary" disabled={busy||!draft.skillKey.trim()||!draft.label.trim()} onClick={saveSkill}>Save / Replace</button></div></div>}
    {note&&<div className="agent-note">{note}</div>}
  </aside></div>
}
